GET http://localhost:3000/


###
POST http://localhost:3000/api/v1/user/singup
Content-Type: application/json

{
    "name": "tqnguyen",
    "email": "tqnguyen259@gmail.com",
    "password": "123456",
    "passwordConfirm": "123456"
}


###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}


###
POST http://localhost:3000/api/v1/user/forgot-password
Content-Type: application/json

{
    "email": "rumtqn@gmail.com"
}



###
GET http://localhost:3000/api/v1/user/user-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzJiMjdkZDkwYTJjMGY3OGM0NTRkMiIsImlhdCI6MTY5OTA5MDgwOCwiZXhwIjoxNzAzNDEwODA4fQ.7i25U0NzzdzHy750O-i3eSWzpHBXTPB-q5LkAXO98yQ



###
PUT http://localhost:3000/api/v1/user/change-profile-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzJiM2FlMWVlODUyMzkwODBjOGQyOCIsImlhdCI6MTY5OTYxNzUxOCwiZXhwIjoxNzAzOTM3NTE4fQ.gPlfGX8aH2ckQWyR4d0rUGgQ7R_Y5OGp8CFMpJJ0mMY

{
    "name": "rumtqnsict23"
}


###
PUT http://localhost:3000/api/v1/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzkyMTc3MmE5ZGFkMTI0MDg0NWNlYiIsImlhdCI6MTY5OTE4MDQwMCwiZXhwIjoxNzAzNTAwNDAwfQ.fBepGJxmlTGGWM8AfzUN9RP0NocJIREKyKVnof93wsw

{
    "currentPassword": "1234567",
    "newPassword": "123456",
    "passwordConfirm": "123456"
}



###
GET http://localhost:3000/api/v1/NFTs/nft-created-by-user/6532b27dd90a2c0f78c454d2



###
GET http://localhost:3000/api/v1/NFTs/


###
POST http://localhost:3000/api/v1/NFTs/
Content-Type: application/json

{
    "title": "NFT test",
    "description": "test desc",
    "category": "Nature",
    "image": "12345",
    "address": "0x1231231233",
    "email": "tqnguyen@gmail.com"
}